classDiagram
  class streaming {
  }
  class frame_buffer {
  }
  class go2rtc_manager {
  }
  class hls_service {
  }
  class stream_keepalive {
  }
  class webrtc_signaling {
  }
  stream_keepalive --> go2rtc_manager
  webrtc_signaling --> go2rtc_manager
